version: '3.3'
services:
   web:
       build:
        context: .
        dockerfile: Dockerfile
       command: gunicorn stripePay.wsgi:application --bind 0.0.0.0:8000
       expose:
           - 8000
   server:
     image: nginx:alpine
     restart: always
     depends_on:
       - web
     ports:
       - '80:80'
       - '443:443'
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf

