version: '3.3'
services:
   web:
       build:
        context: .
        dockerfile: Dockerfile.prod
       command: gunicorn stripePay.wsgi:application --bind 0.0.0.0:8000
       expose:
           - 8000
   nginx:
     build: ./nginx
     ports:
       - 1337:80
     depends_on:
       - web
